
name: Deploy to EC2
on:
  push:
    branches:
      - production/releases

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop ttm-bot-app
            cd food-randomizer-bot/
            git pull
            docker rmi ttm-bot
            docker build -t ttm-bot .
            docker run --rm -it --name ttm-bot-app ttm-bot
