
name: Deploy to EC2
on:
  push:
    branches:
      - releases/production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ $(docker ps -a -q -f name=ttm-bot-app | wc -l) -gt 0 ]; then
              echo "Container exists, stopping and removing..."
              docker stop ttm-bot-app
            else
              echo "Container does not exist, no need to stop or remove."
            fi
            cd food-randomizer-bot/
            git pull
            docker rmi ttm-bot
            docker build -t ttm-bot .
            docker run --rm --name ttm-bot-app ttm-bot
